### ISSUE TITLE
Sass in `*.astro` file `<style>` tags don't have proper syntax highlighting

### ISSUE THREAD

**Issue by adamjohnson** [Destiner/sublime-astro#2]
This is easiest to understand via screenshots:

## Sublime Text (no highlighting)

![Sublime Text screenshot of a style tag with Sass inside (not highlighted)](https://user-images.githubusercontent.com/575865/148598362-45039574-21d7-4671-a13a-d28d069ac431.png)

## VS Code (what it should look like)

![VS Code screenshot of a style tag with Sass inside (highlighted)](https://user-images.githubusercontent.com/575865/148598418-168671c1-4e05-4812-95b8-0e71ee8103b4.png)

[Docs for using Sass in Astro](https://docs.astro.build/en/guides/styling/index.html#-css-preprocessors-sass-stylus-etc)

**Comment by deathaxe** [comment]
Fixed by Astro 2.0.0 (now on https://github.com/SublimeText/Astro)

Note: [Sass](https://packagecontrol.io/packages/Sass) package is required for syntax highlighting.

**Comment by adamjohnson** [comment]
Works, thanks!
